title: WarLUG
email: spotkania@warszawa.linux.org.pl
description: >
  Warszawska Grupa Użytkowników Linuksa
url: "http://warszawa.linux.org.pl"
permalink: pretty

markdown: kramdown

plugins:
  - jekyll-feed

exclude:
  - .jekyll-cache/
  - .sass-cache/
  - Gemfile*
  - gemfiles/
  - Makefile 
  - README.md
  - vendor
